export {default as Category} from './category/Category'
export {default as Product} from './product/Product'
export {default as users} from './users/Users'
export {default as Home} from './home/Home'
export {default as PageNotFound} from './home/PageNotFound'