export const GET_ACCPAYMENT_REQUEST = 'GET_ACCPAYMENT_REQUEST';
export const GET_ACCPAYMENT_SUCCEED = 'GET_ACCPAYMENT_SUCCEED';
export const GET_ACCPAYMENT_FAILED = 'GET_ACCPAYMENT_FAILED';

export const UPDATE_ACCPAYMENT_REQUEST = 'UPDATE_ACCPAYMENT_REQUEST';
export const UPDATE_ACCPAYMENT_SUCCEED = 'UPDATE_ACCPAYMENT_SUCCEED';

export const TOPUP_REQUEST = 'TOPUP_REQUEST';
export const TOPUP_SUCCEED = 'TOPUP_SUCCEED';

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST';
export const PAY_ORDER_SUCCEED = 'PAY_ORDER_SUCCEED';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCEED = 'CANCEL_ORDER_SUCCEED';

export const CLOSE_ORDER_REQUEST = 'CLOSE_ORDER_REQUEST';
export const CLOSE_ORDER_SUCCEED = 'CLOSE_ORDER_SUCCEED';

export const TARIK_UANG_REQUEST = 'TARIK_UANG_REQUEST';
export const TARIK_UANG_SUCCEED = 'TARIK_UANG_SUCCEED';
